export const DUNGEONS = [
  {
    dungeonName: "Antre du Dragon Cochon",
    boss: "Dragon Cochon",
    position: [-1, 33],
    levelRange: "100-110",
    imageUrl: "",
  },
  {
    dungeonName: "Antre du Kralamoure Géant",
    boss: "Kralamoure Géant",
    position: [-60, -8],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Arche d'Otomaï",
    boss: "Gourlo le Terrible",
    position: [-55, -4],
    levelRange: "90-100",
    imageUrl: "",
  },
  {
    dungeonName: "Belvédère d'Ilyzaelle",
    boss: "Ilyzaelle",
    position: [-63, -100],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Canopée du Kimbo",
    boss: "Kimbo",
    position: [-54, 16],
    levelRange: "170-180",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon d'Incarnam",
    boss: "Milimilou",
    position: [6, 5],
    levelRange: "10-20",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon de Moon",
    boss: "Moon",
    position: [31, 8],
    levelRange: "100-110",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon de Nowel",
    boss: "Sapik",
    position: [-63, -100],
    levelRange: "60-70",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Abraknydes",
    boss: "Abraknyde Ancestral",
    position: [-9, -14],
    levelRange: "90-100",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Blops",
    boss: "Blops Royaux",
    position: [-25, -17],
    levelRange: "60-70",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Bouftous",
    boss: "Bouftou Royal",
    position: [2, -34],
    levelRange: "25-35",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Bulbes",
    boss: "Bulbig",
    position: [19, -22],
    levelRange: "40-50",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Bworks",
    boss: "Bworkette",
    position: [-5, 10],
    levelRange: "50-60",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Canidés",
    boss: "Meulou",
    position: [-24, 1],
    levelRange: "100-110",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Champs",
    boss: "Tournesol Affamé",
    position: [7, -25],
    levelRange: "20-30",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Craqueleurs",
    boss: "Craqueleur Légendaire",
    position: [-3, -7],
    levelRange: "50-60",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Firefoux",
    boss: "Péki Péki",
    position: [28, -52],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Kitsounes",
    boss: "Tanukouï San",
    position: [32, -38],
    levelRange: "150-160",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Larves",
    boss: "Shin Larve",
    position: [-2, -5],
    levelRange: "60-70",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Rats de Bonta",
    boss: "Rat Blanc",
    position: [-35, -59],
    levelRange: "110-120",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Rats de Brâkmar",
    boss: "Rat Noir",
    position: [-26, 31],
    levelRange: "110-120",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Rats du Château d'Amakna",
    boss: "Sphincter Cell",
    position: [6, -9],
    levelRange: "160-170",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Scarafeuilles",
    boss: "Scarabosse Doré",
    position: [1, 26],
    levelRange: "50-60",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Squelettes",
    boss: "Chafer",
    position: [10, 15],
    levelRange: "40-50",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon des Tofus",
    boss: "Batofu",
    position: [5, 6],
    levelRange: "40-50",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon du Bworker",
    boss: "Bworker",
    position: [-21, 12],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon du Chêne Mou",
    boss: "Chêne Mou",
    position: [-9, -14],
    levelRange: "160-170",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon du Koulosse",
    boss: "Koulosse",
    position: [-17, 8],
    levelRange: "100-110",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon du Maitre Corbac",
    boss: "Maitre Corbac",
    position: [-20, -62],
    levelRange: "100-110",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon du Tofu Royal",
    boss: "Tofu Royal",
    position: [5, 6],
    levelRange: "120-130",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon ensablé",
    boss: "Mob l'Éponge",
    position: [13, -28],
    levelRange: "20-30",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon Fungus",
    boss: "Ougah",
    position: [-18, 28],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Donjon Wabbit",
    boss: "Wa Wabbit",
    position: [24, -13],
    levelRange: "160-170",
    imageUrl: "",
  },
  {
    dungeonName: "Forgeron",
    boss: "Coffre des Forgerons",
    position: [13, 21],
    levelRange: "40-50",
    imageUrl: "",
  },
  {
    dungeonName: "Goulet du Rasboul",
    boss: "Silf le Rasboul Majeur",
    position: [-51, 9],
    levelRange: "110-120",
    imageUrl: "",
  },
  {
    dungeonName: "Grotte Hesque",
    boss: "Corailleur Magistral",
    position: [-59, 15],
    levelRange: "60-70",
    imageUrl: "",
  },
  {
    dungeonName: "Laboratoire du Tynril",
    boss: "Tynril",
    position: [-53, 20],
    levelRange: "140-150",
    imageUrl: "",
  },
  {
    dungeonName: "Labyrinthe du Minotoror",
    boss: "Minotoror",
    position: [-42, -17],
    levelRange: "120-130",
    imageUrl: "",
  },
  {
    dungeonName: "Labyrinthe du Minotot",
    boss: "Minotot",
    position: [-42, -17],
    levelRange: "180-190",
    imageUrl: "",
  },
  {
    dungeonName: "Repaire de Skeunk",
    boss: "Skeunk",
    position: [-20, 10],
    levelRange: "120-130",
    imageUrl: "",
  },
  {
    dungeonName: "Repaire des Pandikazes",
    boss: "Maître Pandore",
    position: [18, -36],
    levelRange: "120-130",
    imageUrl: "",
  },
  {
    dungeonName: "Sanctuaire des Dragoeufs",
    boss: "Crocabulia",
    position: [-3, 24],
    levelRange: "120-130",
    imageUrl: "",
  },
  {
    dungeonName: "Sanctuaire du Qu'Tan",
    boss: "Qu'Tan",
    position: [-58, -8],
    levelRange: "190-200",
    imageUrl: "",
  },
  {
    dungeonName: "Sanctuaire des familiers",
    boss: "Familiers",
    position: [-7, -1],
    levelRange: "1-10",
    imageUrl: "",
  },
];
